name: Docker Build - ghcr
description: Build image using buildx
inputs:
  image-name:
    required: true
    description: Image name
  tag:
    required: true
    description: Image tag
  github-token:
    required: true
    description: GitHub token for login
  registry:
    required: true
    description: Container registry (e.g., ghcr.io/llm-d)
  context:
    required: false
    description: Build context path (defaults to repository root)
    default: '.'
  dockerfile:
    required: false
    description: Path to Dockerfile relative to context (defaults to Dockerfile in context)
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.github-token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Print image info
      run: |
        echo "Image name: ${{ inputs.image-name }}"
        echo "Tag: ${{ inputs.tag }}"
        echo "Registry: ${{ inputs.registry }}"
      shell: bash

    - name: Build image and push
      run: |
        DOCKERFILE_ARG=""
        if [ -n "${{ inputs.dockerfile }}" ]; then
          DOCKERFILE_ARG="-f ${{ inputs.dockerfile }}"
        fi
        docker buildx build \
          --platform linux/amd64 \
          ${DOCKERFILE_ARG} \
          -t ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.tag }} \
          --push ${{ inputs.context }}
      shell: bash
