name: Docker Build - ghcr
description: Build image using buildx
inputs:
  image-name:
    required: true
    description: Image name
  tag:
    required: true
    description: Image tag
  github-token:
    required: true
    description: GitHub token for login
  registry:
    required: true
    description: Container registry (e.g., ghcr.io/llm-d)
  context:
    required: false
    description: Build context path (defaults to repository root)
    default: '.'
  dockerfile:
    required: false
    description: Path to Dockerfile relative to context (defaults to Dockerfile in context)
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      run: echo "${GITHUB_TOKEN}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Print image info
      run: |
        echo "Image name: ${IMAGE_NAME}"
        echo "Tag: ${TAG}"
        echo "Registry: ${REGISTRY}"
      shell: bash
      env:
        IMAGE_NAME: ${{ inputs.image-name }}
        TAG: ${{ inputs.tag }}
        REGISTRY: ${{ inputs.registry }}

    - name: Build image and push
      run: |
        DOCKERFILE_ARG=""
        if [ -n "${DOCKERFILE}" ]; then
          DOCKERFILE_ARG="-f ${DOCKERFILE}"
        fi
        docker buildx build \
          --platform linux/amd64 \
          ${DOCKERFILE_ARG} \
          -t "${REGISTRY}/${IMAGE_NAME}:${TAG}" \
          --push "${CONTEXT}"
      shell: bash
      env:
        DOCKERFILE: ${{ inputs.dockerfile }}
        REGISTRY: ${{ inputs.registry }}
        IMAGE_NAME: ${{ inputs.image-name }}
        TAG: ${{ inputs.tag }}
        CONTEXT: ${{ inputs.context }}
